insert into Ingredient values ('FLTO', 'Flour Tortilla', 'WRAP');
insert into Ingredient values ('COTO', 'Corn Tortilla', 'WRAP');
insert into Ingredient values ('GRBF', 'Ground Beef', 'PROTEIN');
insert into Ingredient values ('CARN', 'Carnitas', 'PROTEIN');
insert into Ingredient values ('TMTO', 'Diced Tomatoes', 'VEGGIES');
insert into Ingredient values ('LETC', 'Lettuce', 'VEGGIES');
insert into Ingredient values ('CHED', 'Cheddar', 'CHEESE');
insert into Ingredient values ('JACK', 'Monterrey Jack', 'CHEESE');
insert into Ingredient values ('SLSA', 'Salsa', 'SAUCE');
insert into Ingredient values ('SRCR', 'Sour Cream', 'SAUCE');
insert into Ingredient values ('CHCR', 'Cheese Cream', 'SAUCE');